ChatGPT_LineCreat/Controllers/ChatGptController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using System.Web.Http;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;

namespace ChatGPT_LineCreat.Controllers
{
    public class ChatGptController : ApiController
    {

        private static HttpClient httpClient = new HttpClient();

        /// <summary>
        /// 一句話的問答與回應
        /// </summary>
        /// <param name="Param">使用者文字輸入</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<string> ChatGPTAns(string Param)
        {
            string apiKey = "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";
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            ///httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");

            var jsonContent = new
            {
                prompt = Param,
                model = "text-davinci-003",
                max_tokens = 1000
            };
            var responseContent = await httpClient.PostAsync("https://api.openai.com/v1/completions",
                                    new StringContent(JsonConvert.SerializeObject(jsonContent), Encoding.UTF8, "application/json")
                                );

            var resContext = await responseContent.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<dynamic>(resContext);
            if (data == null)
            {
                return "Data Error";
            }
            return data.choices[0].text;
        }



    }
}

ChatGPT_LineCreat/Controllers/HomeController.cs
using ChatGPT_LineCreat.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ChatGPT_LineCreat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProcessInput(string inputText = "測試ok")
        {
            string result = "You entered: " + inputText;
            return Content(result);
        }
    }
}

ChatGPT_LineCreat/Controllers/LineBotController.cs
using ChatGPT_LineCreat.Domain;
using ChatGPT_LineCreat.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Web.Http;
using System.Web.Mvc;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;
using ControllerBase = Microsoft.AspNetCore.Mvc.ControllerBase;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;

namespace ChatGPT_LineCreat.Controllers
{
    //public class LogMessageResponse
    //{
    //    public string lastLogMessage { get; set; }
    //}



    [ApiController]
    [Route("api/[controller]")]
    public class LineBotController : ControllerBase
    {
        // 宣告 service
        private readonly LineBotService _lineBotService;
        public string lastLogMessage;
        //private UdpServiceController _udpServiceController;
        //private UdpService udpService;

        private readonly string channel_Access_Token = "UvZMLvpeD3+HW+rTns/3QmnzWEpzctuVb8M64rplTT6aF8ShPGxMe6Xuacl751A0q5JzKr36LlasT++mPGtcxRvm7fw1zu5WE6ZgjA0DXNW5oaU8Ko5EbgU8vV88oTHOhb+5drh4Bz5jyF+AN0Q+zwdB04t89/1O/w1cDnyilFU=";


        // constructor
        public LineBotController()
        {
            //udpService = new UdpService(8080);
            //_udpServiceController = new UdpServiceController(8080);
            _lineBotService = new LineBotService();
            _lineBotService.LogEvent += LogMessageToView; // 訂閱事件
        }

        [HttpPost]
        [Route("Webhook")]
        public ActionResult Webhook(WebhookRequestBodyDto body)
        {
            try
            {
                _lineBotService.ReceiveWebhook(body); // 呼叫 Service

                // 接收UDP數據
                //string udpData = _udpServiceController.ReceiveData();

                //string receivedData = udpServiceController.ReceiveData();

                return Content("UDP數據成功接收：" + lastLogMessage);
            }
            catch (Exception ex)
            {
                return Content("發生錯誤：" + ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Post()
        {
            var replyEvent = new ReplyEvent(channel_Access_Token);

            try
            {
                //Get Post RawData (json format)
                var req = HttpContext.Request;
                using (var bodyReader = new StreamReader(stream: req.Body,
                    encoding: Encoding.UTF8,
                    detectEncodingFromByteOrderMarks: false,
                    bufferSize: 1024, leaveOpen: true))
                {
                    var body = await bodyReader.ReadToEndAsync();
                    var lineReceMsg = ReceivedMessageConvert.ReceivedMessage(body);

                    if (lineReceMsg != null && lineReceMsg.Events[0].Type == WebhookEventType.message.ToString())
                    {
                        //get user msg
                        var userMsg = lineReceMsg.Events[0].Message.Text;

                        //send reply msg
                        var txtMessage = new TextMessage(userMsg);
                        await replyEvent.ReplyAsync(lineReceMsg.Events[0].ReplyToken,
                                                   new List<IMessage>() {
                                                       txtMessage
                                                   });
                    }
                }
            }
            catch (Exception ex)
            {
                return Ok();
            }
            return Ok();

        }

        //[HttpPost]
        //[Route("Webhook")]
        //public ActionResult Webhook(string inputText = "測試成功")
        //{
        //    string result = "You entered: " + inputText;
        //    return Content(result);
        //}

        //[HttpGet]
        //public JsonResult GetData()
        //{
        //    //string data = udpService.ReceiveData();
        //    string data = "111";
        //    var datas = JsonConvert.SerializeObject(data);
        //    //return JsonResult(data, JsonRequestBehavior.AllowGet); ;
        //    return Json(new { datas }, JsonRequestBehavior.AllowGet);
        //}

        //private JsonResult Json(object value, JsonRequestBehavior allowGet)
        //{
        //    throw new NotImplementedException();
        //}

        public void LogMessageToView(string logMessage)
        {
            // 將 logMessage 儲存起來
            lastLogMessage = logMessage;
        }
    }

}

ChatGPT_LineCreat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!DOCTYPE html>
<html>
<head>
    <title>Call Controller Example</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <h1>Call Controller Example</h1>

    <form id="inputForm" method="post" action="@Url.Action("ChatGPTAns", "ChatGpt")">
        <label for="inputText">Chat Text:</label>
        <input type="text" id="inputText" name="Param" />
        <button type="submit">Enter</button>
    </form>

    @* <form id="lastLogMessage" method="post" action="@Url.Action("Webhook", "LineBot")"> 
    </form>*@

    <div id="lastLogMessage">資料內容</div>
    <p>@Model</p>

    <div id="result"></div>

    
    <script>
        $(document).ready(function () {
            $('#inputForm').submit(function (event) {
                event.preventDefault();


                var formData = $(this).serialize();
                $.post($(this).attr('action'), formData, function (data) {
                    console.log(data);
                    // 把取得的回應添加顯示在下方
                    $('#result').append('<p>Chat Text: ' + $('#inputText').val() + '</p>');
                    $('#result').append('<p>Response: ' + data + '</p>');

                    // 清空輸入框内容
                    $('#inputText').val('');
                });
            });
        });

        // $(document).ready(function () {
        //     $.ajax({
        //         type: 'POST',
        //         url: '/api/LineBot/Webhook',
        //         data: {}, // post内容
                
        //         success: function (data) {
        //             console.log(data);

        //             $('#lastLogMessage').append('<p>Response: ' + data + '</p>'); // 从返回的JSON对象中获取logMessage值并显示在页面上
        //         },
        //         error: function () {
        //             $('#lastLogMessage').text('Error occurred.');
        //         }
        //     });
        // });


        function refreshData() {
            $.ajax({
                url: '@Url.Action("ProcessInput")',
                type: 'POST',
                dataType: 'json',
                success: function (result) {
                    $('#lastLogMessage').html(result.data);
                    setTimeout(refreshData, 1000); // 刷新间隔（1秒）
                },
                error: function () {
                    console.log('Failed to fetch data.');
                    setTimeout(refreshData, 1000); // 刷新间隔（1秒）
                }
            });
        }

        $(document).ready(function () {
            refreshData(); // 初始化刷新数据
        });
    </script>







</body>
</html>